### ISSUE TITLE
Wrong link to the repo in README

### ISSUE THREAD

**Issue by belgoros** [javalite/javalite-examples#10]
It seems like the link to clone the project `git clone git@github.com:javalite/activeweb-secure.git` indicated in the project `README` file is pointing the deprecated repository. Should it be the one of **javalite-examples** `git@github.com:javalite/javalite-examples.git`?

**Comment by ipolevoy** [comment]
yes, this is correct. All examples  were combined into a single repository  for  easier management of version upgrades every time the framework is released..

**Comment by ipolevoy** [comment]
Updated  the steps: 
https://github.com/javalite/javalite-examples/blob/master/activeweb-secure/README.md

**Comment by belgoros** [comment]
Cool, thank you 👍
