### ISSUE TITLE
Add LocalDate and LocalDateTime suppport

### ISSUE THREAD

**Issue by DolgopolovOleg** [javalite/javalite-examples#26]
Now Model class has `getDate()` and `setDate()` and also `set` methods support `java.sql.Date`. Would be nice to see `java.time.LocalDate` and `java.time.LocalDateTime` support as well.

**Comment by ipolevoy** [comment]
@DolgopolovOleg this is filed under the wrong repo. Can you please file this here: https://github.com/javalite/javalite/issues ?

**Comment by DolgopolovOleg** [comment]
I got it. Just done. 
Closing the issue.
