### ISSUE TITLE
Gradle example: upgrade to a more recent version of gradle wrapper

### ISSUE THREAD

**Issue by cschabl** [javalite/javalite-examples#27]
The HTTP-URL of distributionUrl in gradle-wrapper.properties in the Gradle example doesn't work anymore. Besides, it points to a very old Gradle distribution.

Upgrade the Gradle distribution to the latest one that is compatible with activejdbc-gradle-plugin, which is 5.6.4.
Furthermore, gradle-wrapper.jar is missing in activejdbc-gradle/gradle/wrapper.

(This is a first step to make activejdbc-gradle-plugin compatible with the latest Gradle release 7.1)

**Comment by ipolevoy** [comment]
@cschabl is this for examples only or we require  changes in the framework too?

**Comment by cschabl** [comment]
@ipolevoy, I don't think so. The activejdbc-gradle-plugin has to be adapted to work with Gradle 7.1.
Currently, it seems to work up to Gradle 5.6.
